name: gail_airl_ppo_discrete
channels:
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - autopep8=1.6.0
  - blas=1.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - intel-openmp=2023.2.0
  - intelpython=2023.2.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=12.2.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=21.2.2
  - pycodestyle=2.10.0
  - python=3.8.13
  - readline=8.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.12
  - toml=0.10.2
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - absl-py==1.4.0
      - box2d==2.3.10
      - cachetools==5.3.1
      - charset-normalizer==2.1.1
      - cloudpickle==1.6.0
      - cmake==3.25.0
      - farama-notifications==0.0.4
      - filelock==3.9.0
      - future==0.18.3
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.58.0
      - gym==0.19.0
      - gym-classics==1.0.0
      - gymnasium==0.29.1
      - idna==3.4
      - importlib-metadata==6.8.0
      - jinja2==3.1.2
      - lit==15.0.7
      - markdown==3.4.4
      - markupsafe==2.1.2
      - mpmath==1.2.1
      - networkx==3.0
      - numpy==1.24.1
      - oauthlib==3.2.2
      - pillow==9.3.0
      - protobuf==4.24.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygame==2.5.2
      - pyglet==1.5.0
      - pyyaml==6.0.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - sympy==1.11.1
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.66.1
      - triton==2.0.0
      - typing-extensions==4.4.0
      - urllib3==1.26.13
      - werkzeug==2.3.7
      - zipp==3.16.2
